services:
  - type: web
    name: smart-transaction-control
    env: docker
    plan: free
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://vinothyokesh008009_db_user:T6AEVJBfBWlhYx8q@expense-tracker.hqmyhrg.mongodb.net/
      - key: DB_NAME
        value: smart_transaction_control
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USERNAME
        value: vinothyokesh008009@gmail.com
      - key: SMTP_PASSWORD
        value: hxpdlesdpctsvdmg
      - key: SMTP_FROM_NAME
        value: Secure Online Transaction System
      - key: SMTP_SECURE
        value: tls