<?php
// backend/php/receipt_crud.php
/**
 * Receipt Management for Smart Transaction Control
 * Handles payment receipts for customers, generated by staff/receptionist
 */
require_once __DIR__ . '/../../config.php';
require_once __DIR__ . '/security.php';
require_once __DIR__ . '/session_manager.php';
// Prevent direct access
if (!defined('APP_NAME')) {
    http_response_code(403);
    exit('Direct access not allowed');
}
/**
 * Get receipts (customer sees own; staff/receptionist/admin see all)
 * GET
 */
function getReceipts() {
    requireActiveSession();
    $collection = getCollection('receipts');
    if (!$collection) {
        errorResponse('Database connection error');
    }
    $filter = ['deleted_at' => null];
    if (!isAdmin() && !isStaff() && !isReceptionist()) {
        $filter['user_id'] = new MongoDB\BSON\ObjectId(getCurrentUserId());
    }
    $cursor = $collection->find($filter, ['sort' => ['created_at' => -1], 'limit' => 200]);
    $list = [];
    foreach ($cursor as $r) {
        $list[] = [
            'receipt_id' => (string)$r['_id'],
            'receipt_number' => $r['receipt_number'] ?? '',
            'user_id' => isset($r['user_id']) ? (string)$r['user_id'] : '',
            'amount' => round((float)($r['amount'] ?? 0), 2),
            'currency' => $r['currency'] ?? 'INR',
            'description' => $r['description'] ?? '',
            'payment_method' => $r['payment_method'] ?? 'cash',
            'issued_by' => isset($r['issued_by']) ? (string)$r['issued_by'] : '',
            'created_at' => mongoDateToPHP($r['created_at'] ?? null)->format('Y-m-d H:i:s')
        ];
    }
    successResponse(['receipts' => $list], 'Receipts retrieved');
}
/**
 * Generate a new receipt (staff/receptionist)
 * POST: user_id, amount, description, payment_method
 */
function createReceipt() {
    requireRole(['staff', 'receptionist']);
    $data = getRequestData();
    if (!verifyCSRFToken($data['csrf_token'] ?? '')) {
        errorResponse('Invalid security token');
    }
    $targetUserId = $data['user_id'] ?? '';
    $amount = (float)($data['amount'] ?? 0);
    if (!isValidObjectId($targetUserId)) {
        errorResponse('Invalid user ID');
    }
    if ($amount <= 0 || !validateAmount((string)$amount)) {
        errorResponse('Enter a valid amount');
    }
    $collection = getCollection('receipts');
    if (!$collection) {
        errorResponse('Database connection error');
    }
    $receiptNumber = 'RCP-' . date('Ymd') . '-' . strtoupper(bin2hex(random_bytes(3)));
    $result = $collection->insertOne([
        'user_id' => new MongoDB\BSON\ObjectId($targetUserId),
        'receipt_number' => $receiptNumber,
        'amount' => $amount,
        'currency' => sanitizeInput($data['currency'] ?? 'INR'),
        'description' => sanitizeInput($data['description'] ?? 'Payment'),
        'payment_method' => sanitizeInput($data['payment_method'] ?? 'cash'),
        'issued_by' => new MongoDB\BSON\ObjectId(getCurrentUserId()),
        'created_at' => phpDateToMongo(),
        'updated_at' => phpDateToMongo(),
        'deleted_at' => null
    ]);
    // Notify the customer
    $notifications = getCollection('notifications');
    if ($notifications) {
        $notifications->insertOne([
            'user_id' => new MongoDB\BSON\ObjectId($targetUserId),
            'title' => 'Receipt issued',
            'message' => 'A receipt of ' . $amount . ' has been issued to you. Number: ' . $receiptNumber,
            'type' => 'receipt',
            'read' => false,
            'created_at' => phpDateToMongo()
        ]);
    }
    logActivity('receipt_created', getCurrentUserId(), [
        'receipt_id' => (string)$result->getInsertedId(),
        'amount' => $amount
    ]);
    successResponse([
        'receipt_id' => (string)$result->getInsertedId(),
        'receipt_number' => $receiptNumber
    ], 'Receipt generated successfully');
}
/**
 * Route actions
 */
$method = $_SERVER['REQUEST_METHOD'];
$action = $_GET['action'] ?? '';
switch ($action) {
    case 'get_all':
        if ($method === 'GET') getReceipts();
        break;
    case 'create':
        if ($method === 'POST') createReceipt();
        break;
    default:
        errorResponse('Invalid action');
}
?>
